import { createStore } from 'vuex'

export const store = createStore({
    state: {
        resourceName: "http://temp", //`http://${GetParentResourceName()}`
        show: true,
        showBackground: true,
        device: "tablet",
        time: "17:54",
        apps: [{
            label: "Police",
            color: "deep-orange",
            icon: "local_police",
            route: "/apps/police/home",
            device: "tablet",
        }, ],
        appData: {
            police: {
                auth: true,
                access: {
                    groups: {
                        admin: 2,
                        mod: 1,
                        user: 0
                    },
                    permissions: {
                        example: ["admin", "mod", "user"],
                    },
                },
                user: {
                    name: "Big Trav",
                    group: "user"
                },
                civilians: [
                    { name: 'Latravious Brown', group: 'user', avatar: { src: 'https://i.imgur.com/XK8qpQZ.png', approved: true } },
                    { name: 'Kenny Kona', group: 'user', avatar: { src: 'https://i.gyazo.com/e81a8468b25c5e48d3a543870588217a.png', approved: true } },
                    { name: 'Buck Ryan', group: 'user', avatar: { src: 'https://cdn.discordapp.com/attachments/711085660815228974/809911174454968430/517aa81144f99c00187879954adb38ed.jpg', approved: true } },
                    { name: 'Frankie Delco', group: 'user', avatar: { src: 'https://i.imgur.com/hZRqWHq.png', approved: true } },
                    { name: 'Stephan Polinski', group: 'user', avatar: { src: 'https://i.imgur.com/2aETL01.png', approved: true } },
                    { name: 'Mike Stone', group: 'user', avatar: { src: 'https://i.imgur.com/AG7oq8i.png', approved: true } },
                    { name: 'Leonard Kaneko', group: 'user', avatar: { src: 'https://cdn.discordapp.com/attachments/362996769463861249/753720046408171560/unknown.png', approved: true } },
                    { name: 'Kenny Lennard', group: 'user', avatar: { src: 'https://puu.sh/Gs6us/babf162924.jpg', approved: true } },
                    { name: 'Johnny Bandini', group: 'user', avatar: { src: 'https://i.gyazo.com/c5bb9bbc41ccbcba695f8675212592ba.jpg', approved: true } },
                    { name: 'Drake Chapelle', group: 'user', avatar: { src: 'https://i.gyazo.com/771d6dc788d651af08819d9149b5e02a.png', approved: true } },
                    { name: 'Kelly Price', group: 'user', avatar: { src: 'https://i.gyazo.com/3916cdcc362c4f63ee6f76fe47dabe10.png', approved: true } },
                    { name: 'Jaquan Thuggs', group: 'user', avatar: { src: 'https://i.gyazo.com/fb5cb54bad1fa92848a58069c62a5355.png', approved: true } },
                    { name: 'Jamal Franklin', group: 'user', avatar: { src: 'https://cdn.discordapp.com/attachments/362996769463861249/765359960984387594/unknown.png', approved: true } },
                    { name: 'Bashag Bandini', group: 'user', avatar: { src: 'https://cachedimages.podchaser.com/512x512/aHR0cHM6Ly9jcmVhdG9yLWltYWdlcy5wb2RjaGFzZXIuY29tLzNlZWJkOGFlMDI4Mzk5MjNjZDU4M2Q5ODVlMWZjMWM2LmpwZWc%3D/aHR0cHM6Ly93d3cucG9kY2hhc2VyLmNvbS9pbWFnZXMvbWlzc2luZy1pbWFnZS5wbmc%3D', approved: true } },
                    { name: 'Rob Banks', group: 'user', avatar: { src: 'https://i.imgur.com/LTtRWRR.png', approved: true } },
                    { name: 'Gunnar Redmane', group: 'user', avatar: { src: 'https://i.imgur.com/AuAlufJ.png', approved: true } },
                    { name: 'Tommy Juul', group: 'user', avatar: { src: 'https://i.imgur.com/aRuJzFa.png', approved: true } },
                    { name: 'Tim Robertson', group: 'user', avatar: { src: 'https://i.gyazo.com/ce762e4b436d36318c75aed16b7e62a1.png', approved: true } },
                    { name: 'Jamal Juul', group: 'user', avatar: { src: 'https://i.imgur.com/JOmk0pc.png', approved: true } },
                    { name: 'Patrick Flanery', group: 'user', avatar: { src: 'https://i.gyazo.com/bd21b86c905323310db523c5fbf8f120.jpg', approved: true } },
                    { name: 'Erik Jin', group: 'user', avatar: { src: 'https://puu.sh/Gl825/c45dbd0c34.png', approved: true } },
                    { name: 'Jaxson Mangjeol', group: 'user', avatar: { src: 'https://puu.sh/Gl86o/0a1671b408.png', approved: true } },
                    { name: 'Fredriech Thathird', group: 'user', avatar: { src: 'https://puu.sh/GzApc/064e52be4d.png', approved: true } },
                    { name: 'Nic Sampson', group: 'user', avatar: { src: 'https://puu.sh/Glsaf/f2cb320fa0.png', approved: true } },
                    { name: 'Donny Nought', group: 'user', avatar: { src: 'https://puu.sh/GlsgF/16d1bc56ec.png', approved: true } },
                    { name: 'Rodney Rammathorn', group: 'user', avatar: { src: 'https://i.imgur.com/mgwycN1.png', approved: true } },
                    { name: 'Slug Letti', group: 'user', avatar: { src: 'https://puu.sh/Glt9s/760d8d8250.png', approved: true } },
                    { name: 'Curtis Jones', group: 'user', avatar: { src: 'https://i.imgur.com/9KmOg0W.png', approved: true } },
                    { name: 'Jack Holt', group: 'user', avatar: { src: 'https://i.imgur.com/BdendWL.png', approved: true } },
                    { name: 'Enzo Henrys', group: 'user', avatar: { src: 'https://puu.sh/Gu9XL/0957230952.png', approved: true } },
                    { name: 'Jimmy Croaks', group: 'user', avatar: { src: 'https://pasteboard.co/JpiGqax.png', approved: true } },
                    { name: 'Harry Diggler', group: 'user', avatar: { src: 'https://i.imgur.com/voOY6Je.png', approved: true } },
                    { name: 'Tyler West', group: 'user', avatar: { src: 'https://puu.sh/GoW3y/59e7bf49cb.jpg', approved: true } },
                    { name: 'Andrew Fit', group: 'user', avatar: { src: 'https://i.imgur.com/4Ld965f.png', approved: true } },
                    { name: 'Mace Danger', group: 'user', avatar: { src: 'https://i.imgur.com/WeDrz3T.png', approved: true } },
                    { name: 'Terry Savage', group: 'user', avatar: { src: 'https://i.imgur.com/uqmkf2c.jpg', approved: true } },
                    { name: 'William Davis', group: 'user', avatar: { src: 'https://i.imgur.com/qrSdmpY.png', approved: true } },
                    { name: 'Jonah Hyll', group: 'user', avatar: { src: 'https://cdn.discordapp.com/attachments/805653826966913075/807203028623949834/d54b7c6a0656c3e5546980363850ee9b_2.png', approved: true } },
                    { name: 'Fernando Bonanza', group: 'user', avatar: { src: 'https://i.imgur.com/i3M2mny.png', approved: true } },
                    { name: 'Joe Clark', group: 'user', avatar: { src: 'https://i.imgur.com/PRarDLx.png', approved: true } },
                    { name: 'Jim Walker', group: 'user', avatar: { src: 'https://gyazo.com/412aa80e1fd88027b636085fccb89a98.png', approved: true } },
                    { name: 'Jim Dauterive', group: 'user', avatar: { src: 'https://i.imgur.com/uen3X7t.png', approved: true } },
                    { name: 'Amelia Esposito', group: 'user', avatar: { src: 'https://i.imgur.com/vUqnLzi.jpg', approved: true } },
                    { name: 'Arnold Winslow', group: 'user', avatar: { src: 'https://i.imgur.com/MovwkdX.png', approved: true } },
                    { name: 'Ronald Simmons', group: 'user', avatar: { src: 'https://i.imgur.com/NMYKHva.png', approved: true } },
                    { name: 'Jason Richardson', group: 'user', avatar: { src: 'https://i.imgur.com/7m6XiXM.png', approved: true } },
                    { name: 'Dwayne Jackson', group: 'user', avatar: { src: 'https://cdn.discordapp.com/attachments/711085660815228974/810071885869482004/unknown.png', approved: true } },
                    { name: 'Abel Sampson', group: 'user', avatar: { src: 'https://i.imgur.com/Uxv6Qwx.png', approved: true } },
                    { name: 'Dave Mclean', group: 'user', avatar: { src: 'https://cdn.discordapp.com/attachments/362996769463861249/752504441101484052/unknown.png', approved: true } },
                    { name: 'William Hill', group: 'user', avatar: { src: 'https://i.imgur.com/HWp2tmm.png', approved: true } },
                    { name: 'Bob Abernathy', group: 'user', avatar: { src: 'https://i.imgur.com/GOb9Tm9.png', approved: true } },
                    { name: 'Lexi Lemly', group: 'user', avatar: { src: 'https://i.gyazo.com/3e52de75fec94884649152317e9e16fa.png', approved: true } },
                    { name: 'Zamir Jackson', group: 'user', avatar: { src: 'https://i.imgur.com/l0JY9Le.png', approved: true } },
                    { name: 'Frankie Tribbiani', group: 'user', avatar: { src: 'https://i.imgur.com/nQDGtzG.png', approved: true } },
                    { name: 'Tom Tater', group: 'user', avatar: { src: 'https://i.imgur.com/FIcHEFP.png', approved: true } },
                    { name: 'Ricardo White', group: 'user', avatar: { src: 'https://i.imgur.com/DxjeVWt.png', approved: true } },
                    { name: 'Steve Bean', group: 'user', avatar: { src: 'https://i.imgur.com/cU0BdtJ.png', approved: true } },
                    { name: 'Steven Andriacci', group: 'user', avatar: { src: 'https://i.imgur.com/N7thO1f.png', approved: true } },
                    { name: 'Miyah Andriacci', group: 'user', avatar: { src: 'https://i.imgur.com/ueK8SA3.png', approved: true } },
                    { name: 'Nathan James', group: 'user', avatar: { src: 'https://i.imgur.com/Z82Aee9.png', approved: true } },
                    { name: 'Kaigel Zhang', group: 'user', avatar: { src: 'https://i.imgur.com/YpOdsMm.png', approved: true } },
                    { name: 'Jon Haggard', group: 'user', avatar: { src: 'https://gyazo.com/79912d030a6959a90b10f7406ff56248', approved: true } },
                    { name: 'Curtis Lewis', group: 'user', avatar: { src: 'https://i.imgur.com/7ah5ioy.png', approved: true } },
                    { name: 'Rakeesh Patel', group: 'user', avatar: { src: 'https://cdn.discordapp.com/attachments/362996769463861249/752995289299681310/unknown.png', approved: true } },
                    { name: 'David Young', group: 'user', avatar: { src: 'https://puu.sh/Gv49Q/33702fe5a5.png', approved: true } },
                    { name: 'Carsson Bjorg', group: 'user', avatar: { src: 'https://i.imgur.com/vlkvO8D.png', approved: true } },
                    { name: 'Tim Franklin', group: 'user', avatar: { src: 'https://i.imgur.com/91j4dLS.png', approved: true } },
                    { name: 'Rupert Patel', group: 'user', avatar: { src: 'https://i.imgur.com/jp3U2pE.png', approved: true } },
                    { name: 'Daniel Amos', group: 'user', avatar: { src: 'https://i.imgur.com/h5rJ5vo.png', approved: true } },
                    { name: 'Sofia Walton', group: 'user', avatar: { src: 'https://i.imgur.com/DQ2RnHa.png', approved: true } },
                    { name: 'Sayod Patel', group: 'user', avatar: { src: 'https://cdn.discordapp.com/attachments/362996769463861249/753690894758051911/unknown.png', approved: true } },
                    { name: 'Danny Domingo', group: 'user', avatar: { src: 'https://i.imgur.com/2YM9xqC.png', approved: true } },
                    { name: 'Kyle Summers', group: 'user', avatar: { src: 'https://i.imgur.com/sUvBuav.png', approved: true } },
                ],
                users: [
                    { name: 'Kelly Price', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Bashag Bandini', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Patrick Flanery', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Danny Brody', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Kenny Kona', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'James Falcone', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Benjamin Barker', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Joseph Dwight', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Zhuang Lao', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'William Ramirez', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Theo Jericho', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Johnny Bandini', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Nash Taylor', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Buck Ryan', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'William Harde', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Raphael Thickson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Chance Noonan', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Gunnar Redmane', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ael Leanne', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mason Awki', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Sam Gardner', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Bradley Jones', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'John Miller', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Dwayne Jackson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Luke Jones', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Justin Mozzarelli', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Daisy Jenkins', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Anddy Clam', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Eric Hobbs', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Lee Anderssen', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jack Foreslinger', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Chase Miller', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Chef Noonab', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Steven Daniels', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Rodney Rammathorn', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Tyler Ghost', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Donny Nought', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Chris Bacon', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jay Peralta', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ajax Juul', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Nic Sampson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jason Richardson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'James Cooper', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Gwyn Baxter', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ricky Tarval', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Charlotte Miles', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Amelia Esposito', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Darby Donahue', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Tim Bradford', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'John Dark', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Arnold Winslow', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'James Marsh', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Alexander Montgomery', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ronald Simmons', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Fernando Bonanza', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Randy Tuffins', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Honey Valentine', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Victor Phoenix', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mason Preacher', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Cody Zeal', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Gary Winthorpe', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Carbine Holder', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Elie Kastellanos', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Fidel Hardin', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Eddy Browning', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Daniel Amos', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'James Matthews', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Callum Perry', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Rhae Vallancourt', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Wyatt Lawson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Alexander Parish', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Frank Barnes', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Octavia Hart', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Josiah Shepard', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'D Black', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Darrell Black', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Richard Mcmillen', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Herbert Fane', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'John Beau', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'William Richards', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Devin Rayne', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Camera Man', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jean Laurent', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Fred Rogers', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mark Moore', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mika Stone', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Guawrd Wan', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Gordon Bankton', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Olivia Montgomery', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ryan Polaris', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Michael Crimson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'James Bund', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Diego Secada', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Damian Frost', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'T Eighthundred', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Aaron Cerella', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Sven Stone', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Darnell Black', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Anthony Cappareli', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Emily Reinhart', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Maurice Boscorelli', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Lucas Suanez', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Richard Mongo', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ling Wong', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ling Wong', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Michael Goteborg', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Victor Edwards', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Don Nut', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jacob Ryan', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Joshua White', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mac Mcfly', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Frank Moody', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Phoenix London', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'James Harris', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Marcus Fletcher', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Gus Biggs', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Vic Vindrel', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Raj Gupta', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Leroy Woods', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Donovan Ford', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Donny Gambino', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Josh Smith', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Arnold Williams', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Max Power', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jack Strike', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Tony Schwarz', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Viktor Krum', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ed Banger', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Apollo Lockheart', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Myles Knight', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Moose Johnson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Antonio Gotti', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Juli Castellanos', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Bryson Young', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jayna Bandini', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Bob Johnson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Natalie Turner', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Victor Nokosi', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Cricket Gunn', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Patrick Kuby', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Sammy Falcon', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Adin Walker', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Allegra Scott', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mason Kennedy', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jim Parker', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Bruce Force', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Andrew Bishop', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Emily Aldaine', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Evelynn Seadrop', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Emily Ember-Ford', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Dan Chambers', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Callie Appleby', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Michael Briggs', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Kelly Beefcake', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Kurt Leonard', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Rupert Rude', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ben Walker', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Derek Pederson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Zac Hunter', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Marshall Law', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Emil Crane', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Amir Hawk', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Xavier Carter', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Kirk Woolf', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Reyna Diaz', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Anastasia Moore', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Audrey Storm', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mason Blue', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Deanna Harlow', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Tobias Nash', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Tony Tortellini', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Dean Mustang', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Sarah Dean', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Anthony Lynch', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Sam Bazzi', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Alex Strife', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mackey Swanson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mason Rhodes', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Liam Evans', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'John Tripzzz', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jim Jenkins', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Alex Erickson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ryan Macginnis', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Elisha Wesler', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Christopher Shepard', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Francis Carlos', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Harvey Specter', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'August Brooks', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ricky Vonblicky', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'James Bolton', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Hugo Stiglitz', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Brooke Rose', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Tucker Jefferson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Callie Parker', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Blake Slater', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Anne Dempsey', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Dean Sullivan', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jarek Loki', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'James Amos', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Darryl Spring', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'William Knight', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jason Scorsetter', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Matt Vice', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Richard Dawson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Marucs Freeman', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mike Boscoreli', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Sophia Valentine', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Cody McSwagger', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Ben Carter', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Stryks Sabres', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Cavor Arnom', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Rob Octane', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Alison Blossom', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Madelyn Lemonsquare', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Joe Hunter', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Kyle Jonas', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Otto Milano', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mac McLane', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Mariella Wavey', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Oliver Hurst', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Brad Broseph', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Tim Hurst', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Garry Scott', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Julia Forbes', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'John Fulik', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Sebastion Smith', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'North Brennan', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Michael Hunter', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jericho Bane', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Matias Ramos', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Raven Dylan', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'James Henderson', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Jacob Arnett', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Solomon Kane', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Bernard Moral', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Lily Bloom', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Joseph Harper', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Vergil Winters', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Kyle Cronin', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                    { name: 'Luke Cronin', group: 'user', avatar: { src: 'https://i.imgur.com/6M2Wr.png', approved: false } },
                ],
                navigation: [{
                        path: '/apps/police/home',
                        name: 'Home',
                        icon: 'mdi-home',
                        group: 'user',
                    },
                    {
                        path: '/apps/police/reports',
                        name: 'Reports',
                        icon: 'mdi-file-document',
                        group: 'user',
                    },
                    {
                        path: '/apps/police/warrants',
                        name: 'Warrants',
                        icon: 'mdi-file-search',
                        group: 'user',
                    },
                    {
                        path: '/apps/police/bolos',
                        name: 'Bolos',
                        icon: 'mdi-eye',
                        group: 'user',
                    },
                    {
                        path: '/apps/police/records',
                        name: 'Records',
                        icon: 'mdi-fingerprint',
                        group: 'user',
                    },
                    {
                        path: '/apps/police/admin',
                        name: 'Admin',
                        icon: 'mdi-star',
                        group: 'admin',
                    }
                ],
                warrants: [{
                    id: 1,
                    name: "Eric Milton",
                    creator: "Danny Phantom",
                    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.",
                    mugshot: "https://a.rsg.sc//n/natesw11/n",
                    created_at: 1563560195
                }, ],
                bolos: [{
                    id: 1,
                    name: "Eric Milton",
                    creator: "Danny Phantom",
                    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.",
                    mugshot: "https://a.rsg.sc//n/natesw11/n",
                    created_at: 1563560195
                }, ],
                reports: [],
                announcements: [{
                        id: 1,
                        header: 'Main',
                        icon: "mdi-alarm",
                        description: 'This is a test announcement 1!',
                    },
                    {
                        id: 2,
                        header: 'Promotions',
                        icon: "mdi-alarm",
                        description: 'This is a test announcement 2!',
                    },
                    {
                        id: 3,
                        header: 'Trainings',
                        icon: "mdi-alarm",
                        description: 'This is a test announcement 3!',
                    },
                ],
                reportTypes: [{
                        id: 0,
                        file: "incident.pdf",
                        name: "incident",
                        type: "Incident Report"
                    },
                    {
                        id: 1,
                        file: "arrest.pdf",
                        save: "arrests/",
                        name: "arrest",
                        type: "Arrest Report"
                    },
                    {
                        id: 2,
                        file: "warrant.pdf",
                        save: "warrants/",
                        name: "warrant",
                        type: "Warrant Report"
                    },
                    {
                        id: 3,
                        file: "internalaffairs.pdf",
                        save: "internalaffairs/",
                        name: "internalaffair",
                        type: "IA Report"
                    },
                ]
            },
        }
    },
    mutations: {
        submitReport(state, data) {
            state.reports.push(data)
        },
    },
    actions: {},
    modules: {},
    getters: {
        apps: state => {
            return state.apps.filter(app => app.device === state.device || !app.device);
        },
        appData: (state, getters) => (obj) => {
            let app = getters.appFromRoute;

            if (!state.appData[app])
                return [`${app} doesn't exist`, false];
            if (!state.appData[app][obj])
                return [`${app}.${obj} doesn't exist`, false];

            return [false, state.appData[app][obj]]
        },
        appFromRoute: state => {
            let path = state.route.path;

            if (!path.includes("apps"))
                return false;

            let pathDir = path.split("/");

            return pathDir[2];
        },
        appHasPermission: (state, getters) => (perm) => {
            let app = getters.appFromRoute;
            let data = state.appData[app];

            if (!data)
                return [`${app} doesn't exist`, false];
            if (!data.access || !data.access.groups || !data.access.permissions)
                return [`${app}-app: doesn't support permissions`, false];
            if (!data.user || !data.user.group)
                return [`${app}-app: doesn't support users`, false];
            if (data.access.groups[data.user.group] === undefined)
                return [`${app}-app: ${data.user.group} group doesn't exist`, false];
            if (!data.access.permissions[perm])
                return [`${app}-app: ${perm} permission doesn't exist`, false];

            return [false, data.access.permissions[perm].includes(data.user.group)]
        },
        isTablet: state => {
            return state.device === "tablet";
        },
        isPhone: state => {
            return state.device === "phone";
        },
    }
})